#!/usr/bin/env bash

current_session=$XDG_CURRENT_DESKTOP

set_wallpaper_xfce() {
	dir="${HOME}/.config/hypr/images/gallery"
	monitor="$(xrandr --query | grep " connected" | cut -d" " -f1)"
	BG=$(find "$dir" -type f -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" -o -name "*.webp" | shuf -n1)
	xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor"$monitor"/workspace0/last-image -s "${BG}"
}

set_wallpaper_hyprland() {
	dir="${HOME}/.config/hypr/images/gallery"
	BG="$(find "$dir" -name '*.jpg' -o -name '*.png' | shuf -n1)"
	PROGRAM="swww-daemon"
	trans_type="simple"

	if pgrep "$PROGRAM" >/dev/null; then
		swww img "$BG" --transition-fps 100 --transition-type $trans_type --transition-duration 1
	else
		swww init && swww img "$BG" --transition-fps 100 --transition-type $trans_type --transition-duration 1
	fi
}

set_wallpaper_other() {
	dir="${HOME}/gallery"
	BG="$(find "$dir" -name '*.jpg' -o -name '*.png' | shuf -n1)"
	cat "$BG" > ~/eve/.config/hypr/images/gallery/nix.jpg
	xwallpaper --zoom "$BG"
}

case "$current_session" in
"XFCE")
	set_wallpaper_xfce
	;;
"Hyprland")
	set_wallpaper_hyprland
	;;
*)
	set_wallpaper_other
	;;
esac
